// ══════════════════════════════════════════════════════════════
// QuizRoom.js  —  Colyseus Room (State-Driven Architecture)
//
// ARCHITECTURE PRINCIPLES:
//   1. this.state (QuizRoomState) is the single source of truth.
//   2. Server owns ALL phase transitions, timers, and scoring.
//   3. Clients NEVER drive game progression — they only submit
//      answers and receive state patches.
//   4. room.onMessage() is used ONLY for:
//        - join acknowledgements / errors
//        - one-time notifications (confetti, toasts)
//        - answer submission (client → server)
//        - host commands (start, end, next round)
//   5. Player list sync is via MapSchema patches — zero
//      playersUpdated broadcasts for live score/status changes.
//
// PHASE MACHINE (server-authoritative):
//   lobby → countdown → question → answer_reveal
//   → question (loop) → results → waiting_next_round → lobby
//
// PERFORMANCE TARGET: 100–500 concurrent players
// ══════════════════════════════════════════════════════════════

const { Room }        = require('colyseus');
const { randomBytes } = require('crypto');
const { QuizRoomState, PlayerState, GameSettingsState } = require('./schema/QuizRoomState');

const MAX_PLAYERS         = 500;
const COUNTDOWN_DURATION  = 3;    // seconds before first question
const REVEAL_DURATION     = 4;    // seconds to show answer reveal
const RESULTS_DELAY       = 600;  // ms before showing results page
const RECONNECT_WINDOW    = 120;  // seconds a disconnected player can rejoin

class QuizRoom extends Room {

  // ════════════════════════════════════════
  // LIFECYCLE
  // ════════════════════════════════════════

  onCreate(options) {
    this.maxClients     = MAX_PLAYERS;
    this.setState(new QuizRoomState());

    // Non-schema server-side fields (not synced to clients)
    this.hostSessionId      = null;
    this.hostToken          = null;   // stable secret for host re-claim after refresh
    this.customQuestions    = [];
    this.activeQuestions    = [];
    this.blitzRound         = null;

    // Stable reconnect identity.
    // Each player is issued a random token on first join, stored in their
    // sessionStorage. On page-refresh they send it back; the server maps it
    // to the existing PlayerState (now under a new Colyseus sessionId).
    this._tokenToSessionId  = {};   // token  → current sessionId
    this._sessionIdToToken  = {};   // sessionId → token  (reverse, for cleanup)

    // Cached count of active (non-host, non-exited) players.
    // Maintained incrementally so _checkAllFinished and blitzAnswer
    // never need an O(n) full-scan of the players map per message.
    this._activePlayerCount = 0;

    // Timer handles
    this._phaseTimer        = null;
    this._tickInterval      = null;
    this._blitzRevealTimer  = null;

    if (options.pin) this.roomId = options.pin.toUpperCase();

    // Apply initial settings if provided
    if (options.settings) this._applySettings(options.settings);

    this._registerHandlers();
  }

  onJoin(client, options) {
    const isHost        = !!options.isHost;
    const nick          = (options.nickname || 'Player').slice(0, 24);
    const clientToken   = (options.reconnectToken || '').toString().slice(0, 64);
    const clientHostTok = (options.hostToken || '').toString().slice(0, 64);

    // ── PIN validation ──
    // Colyseus matchmaking routes by roomId, but we enforce the PIN here too
    // so no client can reach the room without supplying the correct code.
    // The check is skipped only when the room itself has no PIN (roomId > 6 chars
    // means it was auto-generated by Colyseus, not set from a host PIN).
    const sentPin = (options.pin || '').toString().toUpperCase().trim();
    const roomHasPin = this.roomId && this.roomId.length <= 6;
    if (roomHasPin && sentPin !== this.roomId) {
      client.send('joinError', { message: '❌ Incorrect PIN. Please check and try again.' });
      return;
    }

    // ── HOST join / re-join ──
    if (isHost) {
      // First-time host: issue a secret host token they store in sessionStorage.
      // On page-refresh the host sends hostToken back → we re-grant ownership
      // under the new sessionId without needing the same socket.
      if (!this.hostToken) {
        // Fresh room — this is the first host connection
        this.hostToken     = this._generateToken();
        this.hostSessionId = client.sessionId;
      } else if (clientHostTok && clientHostTok === this.hostToken) {
        // Host refreshed the page — re-grant ownership to new sessionId
        this.hostSessionId = client.sessionId;
      } else if (!this.hostSessionId) {
        // Host token exists but sessionId is gone (host crashed) — allow re-claim
        this.hostSessionId = client.sessionId;
      } else {
        // Someone else is trying to join as host while a host session is active
        client.send('joinError', { message: '❌ A host is already connected to this room.' });
        return;
      }

      // Ensure host has a PlayerState entry under the current sessionId.
      // If the host refreshed, migrate their old entry to the new sessionId.
      const existingHostEntry = [...this.state.players.entries()].find(([, p]) => p.isHost);
      if (existingHostEntry) {
        const [oldId, hp] = existingHostEntry;
        if (oldId !== client.sessionId) {
          this.state.players.delete(oldId);
          this.state.players.set(client.sessionId, hp);
        }
      } else {
        const hp = new PlayerState();
        hp.nickname = 'Host';
        hp.isHost   = true;
        this.state.players.set(client.sessionId, hp);
      }

      this._reconnectPromises = this._reconnectPromises || {};
      try {
        this._reconnectPromises[client.sessionId] = this.allowReconnection(client, RECONNECT_WINDOW);
      } catch (_) {
        delete this._reconnectPromises[client.sessionId];
      }

      client.send('joinAck', {
        status:    this.state.phase,
        settings:  this._getSettingsPlain(),
        gameMode:  this.state.settings.gameMode,
        questions: this.customQuestions,
        hostToken: this.hostToken,   // client must persist this in sessionStorage
      });

      return;
    }

    // ── PLAYER join / reconnect ──
    // Determine whether this is a token-based reconnect (page refresh / mobile bg)
    // or a genuine Colyseus socket reconnect (short drop, same sessionId preserved).
    let player       = null;
    let isTokenRejoin = false;
    let assignedToken = clientToken;

    // ── FIX 3: Two reconnect systems, one job each ───────────────
    //
    // allowReconnection() — owns short socket drops (< RECONNECT_WINDOW).
    //   Colyseus holds the seat open silently. No PlayerState work needed.
    //   Its promise resolves when the same socket comes back, OR is cancelled
    //   below when the token system takes over for a longer/page-refresh drop.
    //
    // reconnectToken — owns identity migration for page refresh, mobile
    //   suspend, or any drop where the socket sessionId changes.
    //   It does all PlayerState + token-map migration.
    //
    // The key rule: if a token-rejoin fires, it CANCELS the old
    // allowReconnection promise by resolving it (not rejecting — Colyseus's
    // deferred does not expose .reject publicly; resolving it closes the slot
    // cleanly). A fresh allowReconnection promise is then registered for the
    // new sessionId. The two systems never both try to own the same slot.

    if (clientToken && this._tokenToSessionId[clientToken]) {
      // Token-based rejoin: page refresh, mobile background, or long drop.
      const oldSessionId = this._tokenToSessionId[clientToken];
      player = this.state.players.get(oldSessionId);

      if (player && !player.isHost) {
        // 1. Migrate MapSchema entry to the new sessionId.
        this.state.players.delete(oldSessionId);
        this.state.players.set(client.sessionId, player);

        // 2. Update token maps.
        delete this._sessionIdToToken[oldSessionId];
        this._tokenToSessionId[clientToken]      = client.sessionId;
        this._sessionIdToToken[client.sessionId] = clientToken;

        // 3. Cancel the old allowReconnection promise.
        //    We resolve it (not reject) so Colyseus closes the old slot cleanly
        //    without treating it as an error. The new sessionId gets its own
        //    fresh promise registered below after this if/else block.
        this._reconnectPromises = this._reconnectPromises || {};
        const oldPromise = this._reconnectPromises[oldSessionId];
        if (oldPromise) {
          try { oldPromise.resolve(client); } catch (_) {}
          delete this._reconnectPromises[oldSessionId];
        }

        // 4. Force-close the old socket if still connected (stale tab, slow disconnect).
        //    Do this AFTER resolving the promise so Colyseus doesn't see an
        //    unexpected close on a slot it thought was still pending.
        const oldClient = this.clients.find(c => c.sessionId === oldSessionId);
        if (oldClient && oldClient.sessionId !== client.sessionId) {
          oldClient.leave(1000);
        }

        player.exited  = false;
        isTokenRejoin  = true;
      } else {
        // Stale token (player was removed or was a host) — treat as fresh join.
        player        = null;
        assignedToken = this._generateToken();
      }
    }

    // ── Colyseus-native socket reconnect (short drop, same sessionId) ──
    // allowReconnection() already held the seat; onJoin fires again with the
    // same sessionId. PlayerState is intact — just clear the exited flag.
    // Token system is not involved here; no migration needed.
    if (!player) {
      player = this.state.players.get(client.sessionId);
      if (player && !player.isHost) {
        player.exited = false;
        // Keep using the token they were already issued on first join.
        assignedToken = this._sessionIdToToken[client.sessionId] || this._generateToken();
      }
    }

    // Genuinely new player
    if (!player) {
      // Nickname uniqueness guard
      const taken = [...this.state.players.values()].some(
        p => !p.isHost && !p.exited &&
             p.nickname.toLowerCase() === nick.toLowerCase()
      );
      if (taken) {
        client.send('joinError', { message: `❌ Nickname "${nick}" is already taken.` });
        return;
      }

      player = new PlayerState();
      player.nickname = nick;
      player.isHost   = false;

      // Auto-assign blitz team for balance
      if (this.state.settings.gameMode === 'blitz') {
        player.team = this.state.blitzTeamCountA <= this.state.blitzTeamCountB ? 'A' : 'B';
        if (player.team === 'A') this.state.blitzTeamCountA++;
        else                     this.state.blitzTeamCountB++;
      }

      this.state.players.set(client.sessionId, player);
      assignedToken = this._generateToken();
      this._activePlayerCount++; // new non-host player joining
    }

    // Register token maps for this session
    this._tokenToSessionId[assignedToken]      = client.sessionId;
    this._sessionIdToToken[client.sessionId]   = assignedToken;

    // FIX 3: Register a fresh allowReconnection promise for this sessionId.
    // This covers three cases:
    //   a) New player — first promise ever for this sessionId.
    //   b) Colyseus-native socket reconnect — same sessionId, promise already
    //      consumed by Colyseus internally; register a new one for the next drop.
    //   c) Token-rejoin — old promise was resolved/cancelled above; new sessionId
    //      needs its own fresh promise so subsequent short drops are covered.
    // We always overwrite here because any prior promise for this exact sessionId
    // is either already consumed (cases b/c) or doesn't exist (case a).
    // allowReconnection() throws "not joined" when called on a freshly connected
    // client — this is a Colyseus quirk where the client must be in a "leaving"
    // state for the call to succeed. On a brand-new connection the promise won't
    // be registered, but that's fine — onLeave will simply not find it and the
    // default Colyseus behaviour applies. On a genuine reconnect (token-rejoin)
    // the client IS in a leaving state so it works correctly.
    this._reconnectPromises = this._reconnectPromises || {};
    try {
      this._reconnectPromises[client.sessionId] = this.allowReconnection(client, RECONNECT_WINDOW);
    } catch (_) {
      // Fresh connection — allowReconnection not applicable yet. The promise
      // will be registered on their next onLeave/onJoin cycle.
      delete this._reconnectPromises[client.sessionId];
    }

    // ── Send acknowledgement ──
    const ackBase = {
      reconnectToken: assignedToken,   // client MUST persist this in sessionStorage
      settings:       this._getSettingsPlain(),
      gameMode:       this.state.settings.gameMode,
      assignedTeam:   player.team,
      teamAName:      this.state.settings.teamAName,
      teamBName:      this.state.settings.teamBName,
      countA:         this.state.blitzTeamCountA,
      countB:         this.state.blitzTeamCountB,
      score:          player.score,
      correctCount:   player.correctCount,
      eliminated:     player.eliminated,
      finished:       player.finished,
      teamScoreA:     this.state.teamScoreA,
      teamScoreB:     this.state.teamScoreB,
    };

    if (this.state.phase === 'lobby' || this.state.phase === 'waiting_next_round') {
      client.send('joinAck', { ...ackBase, status: 'lobby' });
    } else {
      // Mid-game join or reconnect — send full context so client can resume.
      // Answers are stripped from the questions so players can't read them via DevTools.
      client.send('joinAck', {
        ...ackBase,
        status:          isTokenRejoin ? 'reconnected' : 'active',
        waiting:         !isTokenRejoin,
        activeQuestions: this.activeQuestions.map(({ answer, ...rest }) => rest),
        startTime:       this.state.questionStartedAt,
        globalEndTime:   this._globalEndTime || null,
        questionIndex:   this.state.questionIndex,
        // Survival tracks per-player progress independently of the server's
        // timeout-chain index. Send the player's own next question so the
        // client resumes at the right place, not the server's cursor.
        playerQuestionIndex: player.answeredIndex + 1,
        remainingTime:   this.state.remainingTime,
        phaseEndTime:    this.state.phaseEndTime,
      });
    }

  }

  onLeave(client, consented) {
    // ── Host leaving ──
    // Preserve hostToken + PlayerState for host re-claim on page refresh.
    // hostSessionId is intentionally NOT cleared here — in-flight _isHost()
    // checks keep rejecting commands until the new session claims ownership
    // in onJoin. The host's allowReconnection promise keeps the seat open.
    if (client.sessionId === this.hostSessionId) return;

    const player = this.state.players.get(client.sessionId);
    if (!player) return;

    const inActiveGame = !['lobby', 'waiting_next_round', 'results', 'closed'].includes(this.state.phase);

    if (consented && !inActiveGame) {
      // ── Deliberate leave from lobby / between rounds ──
      // Free the slot immediately: no reconnect window needed.
      player.exited = true;
      this._activePlayerCount = Math.max(0, this._activePlayerCount - 1);

      // Clean up both token maps — this player is gone for good.
      const tok = this._sessionIdToToken[client.sessionId];
      if (tok) {
        delete this._tokenToSessionId[tok];
        delete this._sessionIdToToken[client.sessionId];
      }

      // FIX 3: Cancel the allowReconnection promise so Colyseus releases the
      // seat immediately rather than holding it open for RECONNECT_WINDOW.
      // Resolve (not reject) so Colyseus closes cleanly without logging errors.
      if (this._reconnectPromises) {
        const p = this._reconnectPromises[client.sessionId];
        if (p) { try { p.resolve(client); } catch (_) {} }
        delete this._reconnectPromises[client.sessionId];
      }
      return;
    }

    // ── Mid-game disconnect (or consented leave during active game) ──
    //
    // FIX 3: allowReconnection() is the ONLY thing that holds the seat open here.
    // The token system handles identity migration when the player returns — it does
    // NOT need to touch the reconnect promise at all (that's done in onJoin).
    //
    // What we do NOT do here (intentionally):
    //   - Do NOT mark player.exited — keeps their slot and score intact.
    //   - Do NOT delete _tokenToSessionId[tok] — token system needs it for onJoin.
    //   - Do NOT delete _reconnectPromises[sessionId] — Colyseus needs it to hold
    //     the seat open until the player returns or the window expires.
    //
    // What we DO clean up:
    //   - _sessionIdToToken: the old sessionId is dead. The reverse mapping is
    //     only needed when the socket is live. Removing it prevents the dead
    //     sessionId from being mistaken for a live one.
    const tok = this._sessionIdToToken[client.sessionId];
    if (tok) delete this._sessionIdToToken[client.sessionId];
  }

  onDispose() {
    this._clearAllTimers();
    // Clear all token maps to release memory
    this._tokenToSessionId  = {};
    this._sessionIdToToken  = {};
    this._reconnectPromises = {};
  }

  // ════════════════════════════════════════
  // MESSAGE HANDLERS
  // Only used for commands and one-time events.
  // State sync is via schema patches.
  // ════════════════════════════════════════

  _registerHandlers() {

    // ── Keepalive: client pings every 25s to keep the WebSocket alive on Render ──
    // No-op on the server — just receiving it is enough to reset the idle timer.
    this.onMessage('keepalive', () => {});

    // ── blitzFinished: sent by client when blitz results are shown ──
    // Server has no action to take — this was a legacy client message.
    // Registered here to prevent "onMessage not registered" log noise.
    this.onMessage('blitzFinished', () => {});

    // ── HOST: Start game ──
    this.onMessage('startGame', (client, data) => {
      if (!this._isHost(client)) return;

      const MAX_QUESTIONS = 200;
      this.activeQuestions = (data.questions || [])
        .slice(0, MAX_QUESTIONS)
        .filter(q => q && typeof q.q === 'string' && typeof q.answer === 'number');
      if (!this.activeQuestions.length) {
        client.send('hostError', { message: 'No questions loaded.' });
        return;
      }

      this._applySettings(data.settings || {});

      // Reset all player scores
      this.state.players.forEach((p) => {
        if (p.isHost) return;
        p.score             = 0;
        p.correctCount      = 0;
        p.finished          = false;
        p.eliminated        = false;
        p.alive             = true;
        p.finishedAt        = 0;
        p.blitzCorrectCount = 0;
        p.answeredIndex     = -1;
      });

      // Reset team scores
      this.state.teamScoreA    = 0;
      this.state.teamScoreB    = 0;
      this.state.inSuddenDeath = false;
      this.state.roundNumber++;
      this._suddenDeathRound   = 0; // reset for this game

      // Re-balance blitz teams
      if (this.state.settings.gameMode === 'blitz') {
        this.state.blitzTeamCountA = 0;
        this.state.blitzTeamCountB = 0;
        this.state.players.forEach((p) => {
          if (p.isHost || p.exited) return;
          if (!p.team) {
            p.team = this.state.blitzTeamCountA <= this.state.blitzTeamCountB ? 'A' : 'B';
          }
          if (p.team === 'A') this.state.blitzTeamCountA++;
          else                this.state.blitzTeamCountB++;
        });
        // Recalculate to fix any drift from the above loop
        this._recalcBlitzTeamCounts();
      }

      // Calculate server-authoritative start time and global end time
      const COUNTDOWN_MS = COUNTDOWN_DURATION * 1000 + 800; // countdown + buffer
      const startTime = Date.now() + COUNTDOWN_MS;
      const mode = this.state.settings.gameMode;
      this._globalEndTime = (mode === 'lightning')
        ? startTime + (this.state.settings.timerDuration * 1000)
        : null;

      // Broadcast questions + timing. Players receive a redacted copy (no answers).
      // The host receives the full array so it can display the answer reveal.
      const questionsForPlayers = this.activeQuestions.map(({ answer, ...rest }) => rest);
      const hostClient = this.clients.find(c => c.sessionId === this.hostSessionId);
      if (hostClient) {
        hostClient.send('gameStarted', {
          activeQuestions: this.activeQuestions,
          startTime,
          globalEndTime:   this._globalEndTime,
          settings:        this._getSettingsPlain(),
        });
      }
      this.clients.forEach(c => {
        if (c.sessionId === this.hostSessionId) return;
        c.send('gameStarted', {
          activeQuestions: questionsForPlayers,
          startTime,
          globalEndTime:   this._globalEndTime,
          settings:        this._getSettingsPlain(),
        });
      });

      // Kick off phase machine
      this._recalcActiveCount(); // sync active count before gameplay begins
      // Initialize blitzRound for the first question before countdown fires.
      // This must happen before _startCountdown so the first blitzAnswer from any
      // player is accepted the moment the question phase begins.
      if (this.state.settings.gameMode === 'blitz') {
        this.blitzRound = {
          questionIndex: 0,
          answers:       {},
          revealSent:    false,
        };
      }
      this._startCountdown();
    });

    // ── HOST: End game ──
    this.onMessage('endGame', (client) => {
      if (!this._isHost(client)) return;
      this._endGame();
    });

    // ── HOST: Next round ──
    this.onMessage('nextRound', (client, data) => {
      if (!this._isHost(client)) return;
      this._resetRoom(data.settings || this._getSettingsPlain());
    });

    // ── HOST: Reset ──
    this.onMessage('resetGame', (client) => {
      if (!this._isHost(client)) return;
      this._resetRoom(this._getSettingsPlain());
    });

    // ── HOST: Update settings ──
    this.onMessage('updateSettings', (client, data) => {
      if (!this._isHost(client)) return;
      this._applySettings(data.settings || {});
      // Settings are now in schema — clients receive the patch automatically.
      // Send explicit message only so host UI can react immediately.
      client.send('settingsUpdated', { settings: this._getSettingsPlain() });
    });

    // ── PLAYER: Submit answer ──
    // Server validates: one answer per player per question.
    // Scoring is computed here — client score is IGNORED.
    this.onMessage('submitAnswer', (client, data) => {
      const player = this.state.players.get(client.sessionId);
      if (!player || player.isHost || player.eliminated || player.finished) return;
      if (this.state.phase !== 'question') return; // only accept during question phase

      const qi = data.questionIndex;
      const mode = this.state.settings.gameMode;

      // Reject answers for questions other than the current one.
      // Lightning/blitz: state.questionIndex is authoritative (server drives per-question timer).
      // Classic/survival: players self-advance, so validate against player's own progress
      // (state.questionIndex stays at 0 in classic since there is no per-question server timer).
      if (mode === 'lightning' || mode === 'blitz') {
        if (qi !== this.state.questionIndex) return;
      } else {
        // qi must be exactly the next unanswered question for this player
        if (qi !== player.answeredIndex + 1) return;
      }

      // ── Duplicate submission guard ──
      // answeredIndex is stored in schema so reconnecting clients
      // can't resubmit questions they already answered.
      if (player.answeredIndex >= qi) return;
      player.answeredIndex = qi;

      const q = this.activeQuestions[qi];
      if (!q) return;

      const correct  = data.answer === q.answer;
      const scoring  = this.state.settings.scoringMode;
      const timeSpent = (Date.now() - this.state.questionStartedAt) / 1000;

      // ── Server-side scoring ──
      if (correct) {
        player.correctCount++;
        let points = 1;
        if (mode === 'lightning') {
          // Scale bonus brackets proportionally to the chosen per-question timer.
          // First third of time = 3×, middle third = 2×, last third = 1×.
          const dur = this.state.settings.lightningQDuration || 5;
          const third = dur / 3;
          points = timeSpent <= third ? 3 : timeSpent <= third * 2 ? 2 : 1;
        } else if (scoring === 'speed') {
          points = timeSpent <= 3 ? 3 : timeSpent <= 8 ? 2 : 1;
        }
        player.score += points;
      }

      // ── Send answer result back to the submitting player ──
      // Players receive questions with answers stripped (server security), so the
      // client cannot locally determine correct/wrong or compute authoritative score.
      // We send back the correct index + authoritative score for accurate UI feedback.
      client.send('answerResult', {
        questionIndex: qi,
        correctAnswer: q.answer,
        correct,
        score:        player.score,
        correctCount: player.correctCount,
      });

      // ── Survival: wrong answer = elimination ──
      if (mode === 'survival' && !correct) {
        player.eliminated = true;
        player.alive      = false;
        player.finishedAt = Date.now();
        // Schema patch fires automatically — spectators see it instantly
        this._checkAllFinished();
        return;
      }

      // Schema patch fires automatically — no broadcast needed
      this._checkAllFinished();
    });

    // ── PLAYER: Finished all questions ──
    this.onMessage('playerFinished', (client, data) => {
      const player = this.state.players.get(client.sessionId);
      if (!player || player.isHost || player.finished) return;

      // Verify server-side that the player has actually answered the last question.
      // This prevents a client from sending playerFinished immediately to trigger _endGame.
      const lastIndex = this.activeQuestions.length - 1;
      if (player.answeredIndex < lastIndex) return;

      player.finished    = true;
      player.finishedAt  = Date.now();
      // Score already computed server-side — ignore data.score

      this._checkAllFinished();
    });

    // NOTE: eliminatePlayer is intentionally NOT exposed as a client message.
    // Elimination is server-authoritative only: _onQuestionTimeout() handles
    // survival timeouts. Clients derive their eliminated state from the schema patch.

    // ── PLAYER: Exit lobby ──
    this.onMessage('playerExit', (client) => {
      const player = this.state.players.get(client.sessionId);
      if (player && !player.exited) {
        player.exited = true;
        this._activePlayerCount = Math.max(0, this._activePlayerCount - 1);
        // Clean up token maps so this player cannot ghost-rejoin in a future round.
        // Mirror the deliberate-exit path in onLeave().
        const tok = this._sessionIdToToken[client.sessionId];
        if (tok) {
          delete this._tokenToSessionId[tok];
          delete this._sessionIdToToken[client.sessionId];
        }
        // Release the reconnect seat immediately.
        if (this._reconnectPromises) {
          const p = this._reconnectPromises[client.sessionId];
          if (p) { try { p.resolve(client); } catch (_) {} }
          delete this._reconnectPromises[client.sessionId];
        }
      }
    });

    // ── BLITZ: Answer submission ──
    // All vote aggregation happens server-side.
    this.onMessage('blitzAnswer', (client, data) => {
      const player = this.state.players.get(client.sessionId);
      if (!player || player.isHost) return;
      if (this.state.phase !== 'question') return; // only accept answers during question phase

      const qi = data.questionIndex;

      // If blitzRound is null, the game hasn't started yet or was just reset.
      // Reject any stale in-flight answers from the previous round rather than
      // creating a new blitzRound object that would corrupt the fresh game state.
      if (!this.blitzRound) return;

      // Validate against blitzRound, not state.questionIndex — the server pre-sets
      // blitzRound.questionIndex before transitioning to the next question phase,
      // so answers submitted right as the phase changes are correctly routed.
      // Reject only if the blitz round for this qi was already revealed (stale answer).
      if (this.blitzRound.questionIndex === qi && this.blitzRound.revealSent) return;
      // Also reject if qi is for an already-revealed past question
      if (this.blitzRound.questionIndex > qi) return;

      // Reject if qi is for a future question (shouldn't happen — server drives question index)
      if (this.blitzRound.questionIndex !== qi) return;

      // Reject if reveal already sent for this round
      if (this.blitzRound.revealSent) return;

      // One answer per player per question
      if (this.blitzRound.answers[client.sessionId]) return;

      const q = this.activeQuestions[qi];
      const isCorrect = q && data.answer === q.answer;

      // ── FIX: Increment blitzCorrectCount on server immediately ──
      // This is the authoritative count — client sends blitzFinished but
      // the server had no handler for it, leaving blitzCorrectCount at 0.
      if (isCorrect) {
        player.blitzCorrectCount = (player.blitzCorrectCount || 0) + 1;
      }

      this.blitzRound.answers[client.sessionId] = {
        sessionId: client.sessionId,
        team:      player.team || 'A',   // server-authoritative — never trust data.team
        answer:    data.answer,
        timestamp: Date.now(),           // server clock — never trust data.timestamp
      };

      // ── Broadcast teammate pick letter to same-team players ──
      const senderTeam = player.team || 'A';
      this.clients.forEach(c => {
        if (c.sessionId === client.sessionId) return;
        const teammate = this.state.players.get(c.sessionId);
        if (teammate && teammate.team === senderTeam) {
          c.send('blitzTeammatePicked', { answer: data.answer, questionIndex: qi });
        }
      });

      // Check if all active players have answered.
      // Uses _activePlayerCount (O(1)) instead of scanning the full players map.
      const answered = Object.keys(this.blitzRound.answers).length;
      if (answered >= this._activePlayerCount && this._activePlayerCount > 0 && !this.blitzRound.revealSent) {
        this._sendBlitzReveal(qi);
      }
    });

    // ── BLITZ: Reactions (relay to teammates only) ──
    this.onMessage('blitzReaction', (client, data) => {
      const sender = this.state.players.get(client.sessionId);
      if (!sender) return;
      const safeEmoji = String(data.emoji || '').slice(0, 8); // cap at a few chars
      this.clients.forEach(c => {
        if (c.sessionId === client.sessionId) return;
        const p = this.state.players.get(c.sessionId);
        if (p && p.team === sender.team) {
          c.send('blitzReaction', { emoji: safeEmoji, team: sender.team });
        }
      });
    });

    // ── BLITZ: Signals (relay to teammates only) ──
    this.onMessage('blitzSignal', (client, data) => {
      const sender = this.state.players.get(client.sessionId);
      if (!sender) return;
      const safeText = String(data.text || '').slice(0, 100);
      this.clients.forEach(c => {
        if (c.sessionId === client.sessionId) return;
        const p = this.state.players.get(c.sessionId);
        if (p && p.team === sender.team) {
          c.send('blitzSignal', {
            text:     safeText,
            nickname: sender.nickname,  // server-authoritative nickname
            team:     sender.team,      // server-authoritative team
          });
        }
      });
    });

    // ── QUESTIONS: CRUD (host only) ──
    this.onMessage('addQuestion', (client, data) => {
      if (!this._isHost(client)) return;
      this.customQuestions.push(data.question);
      this.broadcast('questionsUpdated', { questions: this.customQuestions });
    });

    this.onMessage('updateQuestion', (client, data) => {
      if (!this._isHost(client)) return;
      const idx = this.customQuestions.findIndex(q => q.id === data.question.id);
      if (idx !== -1) this.customQuestions[idx] = data.question;
      this.broadcast('questionsUpdated', { questions: this.customQuestions });
    });

    this.onMessage('deleteQuestion', (client, data) => {
      if (!this._isHost(client)) return;
      this.customQuestions = this.customQuestions.filter(q => q.id !== data.id);
      this.broadcast('questionsUpdated', { questions: this.customQuestions });
    });

    this.onMessage('clearQuestions', (client) => {
      if (!this._isHost(client)) return;
      this.customQuestions = [];
      this.broadcast('questionsUpdated', { questions: [] });
    });

    // ── BLITZ: Team selection (fallback — auto-assign is preferred) ──
    // Only permitted during lobby or between rounds; never during active play.
    this.onMessage('selectTeam', (client, data) => {
      if (!['lobby', 'waiting_next_round'].includes(this.state.phase)) return;
      const player = this.state.players.get(client.sessionId);
      if (!player || player.isHost) return;
      const newTeam = data.team === 'A' ? 'A' : data.team === 'B' ? 'B' : null;
      if (!newTeam || newTeam === player.team) return;
      const old  = player.team;
      player.team = newTeam;
      if (old === 'A')       this.state.blitzTeamCountA = Math.max(0, this.state.blitzTeamCountA - 1);
      if (old === 'B')       this.state.blitzTeamCountB = Math.max(0, this.state.blitzTeamCountB - 1);
      if (newTeam === 'A')   this.state.blitzTeamCountA++;
      if (newTeam === 'B')   this.state.blitzTeamCountB++;
      // Schema patch fires automatically
    });
  }

  // ════════════════════════════════════════
  // PHASE MACHINE  (server-authoritative)
  //
  // The server sets this.state.phase and all clients
  // receive a delta patch and react accordingly.
  // No client can set a phase directly.
  // ════════════════════════════════════════

  // ── FIX 2: Single phase-transition gate ─────────────────────
  // ALL phase changes MUST go through _transitionTo().
  // It clears every timer first, sets the phase + phaseEndTime once,
  // then optionally schedules the single next-step callback.
  //
  // Rules enforced here:
  //   1. Clear ALL timers before touching phase — no orphaned intervals.
  //   2. One scheduler per transition — _phaseTimer is the only handle.
  //   3. Nothing else in this file may call this.state.phase = directly
  //      or schedule phase-driving timers independently.
  //
  // @param phase      — the new phase string (must be a valid QuizRoomState phase)
  // @param durationMs — how long this phase lasts (0 = indefinite / no auto-advance)
  // @param nextFn     — optional callback fired after durationMs; if omitted the
  //                     caller is responsible for the next transition.
  _transitionTo(phase, durationMs = 0, nextFn = null) {
    // 1. Kill every live timer — no overlapping phases, ever.
    this._clearAllTimers();

    // 2. Set phase + timing in schema atomically.
    this.state.phase = phase;
    if (durationMs > 0) {
      this.state.phaseEndTime = Date.now() + durationMs;
    }

    // 3. Schedule the ONE next-step callback if provided.
    if (nextFn && durationMs > 0) {
      this._phaseTimer = setTimeout(() => {
        this._phaseTimer = null;
        nextFn();
      }, durationMs);
    }
  }

  // _setPhase is kept as a thin wrapper so existing call-sites that only need
  // a label change (no duration, no auto-advance) still work.
  // It routes through _transitionTo so the log + timer-clear guarantee holds.
  _setPhase(phase) {
    this._transitionTo(phase, 0, null);
  }

  _startCountdown() {
    const durationMs = COUNTDOWN_DURATION * 1000;
    // FIX 1 + FIX 2: set phaseEndTime once, one timer, one path to next phase.
    this.state.remainingTime = COUNTDOWN_DURATION;
    this._transitionTo('countdown', durationMs, () => this._startQuestion(0));
  }

  _startQuestion(index) {
    // Guard: stale timer callbacks must not fire after the game has ended or reset.
    // _transitionTo clears timers before transitions, but if _endGame or _resetRoom
    // were called between when the callback was scheduled and when it fires, this
    // guard prevents a question from overlapping a terminal phase.
    const terminalPhases = ['results', 'waiting_next_round', 'lobby', 'closed'];
    if (terminalPhases.includes(this.state.phase)) return;

    const mode = this.state.settings.gameMode;

    if (index >= this.activeQuestions.length) {
      if (mode === 'blitz') return; // blitz ends via _sendBlitzReveal
      this._endGame();
      return;
    }

    // ── Determine per-question timer duration ──
    let dur = 0;
    if (mode === 'lightning')     dur = this.state.settings.lightningQDuration || 5;
    else if (mode === 'survival') dur = this.state.settings.survivalTimerDuration || 8;
    else if (mode === 'blitz')    dur = this.state.settings.blitzTimerDuration || 12;
    // classic: no per-question timer — global timer set on question 0

    // Set question metadata BEFORE transitioning (clients need it on the phase patch).
    this.state.questionIndex      = index;
    this.state.questionStartedAt  = Date.now();
    if (dur > 0) this.state.remainingTime = dur;

    if (dur > 0) {
      // FIX 2: _transitionTo is the single timer scheduler.
      // It clears all previous timers, sets phaseEndTime, fires _onQuestionTimeout.
      this._transitionTo('question', dur * 1000, () => this._onQuestionTimeout(index));
      // Mirror _phaseTimer → _tickInterval so _clearTickInterval() callers can still reach it.
      this._tickInterval = this._phaseTimer;
    } else {
      // classic: transition to question phase with no auto-advance timer.
      this._transitionTo('question', 0);
      if (mode === 'classic' && index === 0) {
        // Global timer for the whole classic game — started once, drives _endGame.
        this._startGlobalTimer();
      }
    }
  }

  _onQuestionTimeout(index) {
    const mode = this.state.settings.gameMode;

    if (mode === 'survival') {
      // Eliminate all players who haven't answered this question
      this.state.players.forEach((player) => {
        if (player.isHost || player.eliminated || player.finished || player.exited) return;
        if (player.answeredIndex < index) {
          player.eliminated = true;
          player.alive      = false;
          player.finishedAt = Date.now();
        }
      });

      // Check if the game is over before arming the next question's timer.
      // _checkAllFinished calls _endGame() if everyone is done/eliminated.
      // We inspect phase AFTER the call to decide whether to continue.
      this._checkAllFinished();

      // FIX — Survival per-question timer:
      // Survival is client-driven (players self-advance questions), but the server
      // must arm a timeout for EACH question so slow/disconnected players are
      // eliminated correctly.  Without this the timer only fires once (question 0).
      // Only advance if the game is still running (not ended by _checkAllFinished above).
      const terminalPhases = ['results', 'waiting_next_round', 'lobby', 'closed'];
      if (!terminalPhases.includes(this.state.phase)) {
        this._startQuestion(index + 1);
      }
      return;
    }

    if (mode === 'blitz') {
      // Force reveal for blitz questions that timed out
      if (this.blitzRound && !this.blitzRound.revealSent) {
        this._sendBlitzReveal(index);
      }
      return;
    }

    if (mode === 'lightning') {
      // Broadcast the correct answer to ALL players before advancing.
      // In lightning mode players don't self-submit on timeout — the server
      // must tell everyone the correct answer so they can display it during
      // the answer_reveal phase. Without this, clients that didn't answer
      // have no correct-answer data and may mis-render the reveal screen.
      const q = this.activeQuestions[index];
      if (q) {
        this.broadcast('questionReveal', {
          questionIndex: index,
          correctAnswer: q.answer,
        });
      }
      this._advanceQuestion(index);
    }
    // classic: global timer handles end-of-game
  }

  _advanceQuestion(currentIndex) {
    // FIX 2: _transitionTo clears timers and gates the single next-step callback.
    this._transitionTo('answer_reveal', REVEAL_DURATION * 1000,
      () => this._startQuestion(currentIndex + 1));
  }

  _endGame() {
    // FIX 2: _transitionTo clears all timers before setting 'results'.
    // The idempotent check here prevents double-calls from _checkAllFinished
    // and a simultaneous timer callback both firing _endGame.
    if (this.state.phase === 'results' || this.state.phase === 'waiting_next_round') return;

    // Transition to results, then auto-advance to waiting_next_round after 8s.
    this._transitionTo('results', 8000, () => {
      if (this.state.phase === 'results') {
        this._transitionTo('waiting_next_round', 0);
      }
    });

    this.broadcast('gameEnded', {});
  }

  _resetRoom(newSettings) {
    const _prevPhase = this.state.phase;
    const _prevMode  = this.state.settings && this.state.settings.gameMode;
    const _newMode   = (newSettings && newSettings.gameMode) || _prevMode;
    this._clearAllTimers();

    // Reset schema state
    // FIX 2: use _transitionTo even here so the log and timer guarantee holds.
    // _clearAllTimers was already called above, so this is safe to call directly.
    this.state.phase            = 'lobby'; // direct set is safe here — _clearAllTimers ran above
    this.state.questionIndex    = -1;
    this.state.remainingTime    = 0;
    this.state.phaseEndTime     = 0;
    this.state.teamScoreA       = 0;
    this.state.teamScoreB       = 0;
    this.state.blitzTeamCountA  = 0;
    this.state.blitzTeamCountB  = 0;
    this.state.inSuddenDeath    = false;
    this.state.questionStartedAt = 0;

    // Reset all player schema fields
    const keepTeams = (newSettings && newSettings.gameMode === 'blitz') ||
                      (!newSettings && this.state.settings.gameMode === 'blitz');
    const toDelete = [];
    this.state.players.forEach((player, playerId) => {
      if (player.isHost) return;
      // If this player's token was deleted (deliberate exit from lobby), remove their slot
      // entirely rather than resurrecting them with exited=false.
      // A deliberately exited player has no entry in _tokenToSessionId.
      const tok = this._sessionIdToToken[playerId];
      if (player.exited && !tok && !this._tokenToSessionId[Object.keys(this._tokenToSessionId).find(t => this._tokenToSessionId[t] === playerId)]) {
        toDelete.push(playerId);
        return;
      }
      player.score             = 0;
      player.correctCount      = 0;
      player.finished          = false;
      player.eliminated        = false;
      player.alive             = true;
      player.finishedAt        = 0;
      player.exited            = false;
      player.blitzCorrectCount = 0;
      if (!keepTeams) player.team = '';
      player.answeredIndex     = -1;
    });
    toDelete.forEach(id => this.state.players.delete(id));

    this.activeQuestions = [];
    this.blitzRound      = null;
    this._globalEndTime  = null;
    this._suddenDeathRound = 0; // reset sudden-death counter for next round

    if (newSettings) this._applySettings(newSettings);

    // Re-sync team counts and active count from actual player values (post-reset ground truth)
    this._recalcActiveCount();
    if (this.state.settings.gameMode === 'blitz') {
      this._recalcBlitzTeamCounts();
    }

    // broadcast() is the reliable path — handles disconnected/closing sockets gracefully.
    // forEach c.send() can silently drop messages for clients in a closing state,
    // which would leave players stuck on the results screen forever.
    const _broadcastPayload = { settings: this._getSettingsPlain(), players: this._getPlayersPlain() };
    this.broadcast('roundReset', _broadcastPayload);

    // For blitz: send each player their server-authoritative team assignment.
    // Sent AFTER roundReset so the client has already reset blitzState before this arrives.
    // Wrapped in try/catch per-client so one bad socket never blocks the rest.
    if (this.state.settings.gameMode === 'blitz') {
      this.clients.forEach(c => {
        const p = this.state.players.get(c.sessionId);
        if (!p || p.isHost) return;
        const team = p.team || null;
        try { c.send('blitzTeamAssign', { team }); } catch (e) {
        }
      });
    }

  }

  // ════════════════════════════════════════
  // GLOBAL TIMER  (classic mode only)
  // Called once on question 0. Sets phaseEndTime for client animation
  // and schedules a single server-side _endGame callback.
  // Uses _tickInterval so _clearAllTimers() can reach it independently
  // of the phase-transition _phaseTimer.
  // ════════════════════════════════════════

  _startGlobalTimer() {
    // Belt-and-suspenders: clear _tickInterval only (phase timer may be null at this point).
    this._clearTickInterval();
    const dur = this.state.settings.timerDuration;
    this.state.remainingTime = dur;
    // FIX 1: set phaseEndTime once — client animates from this, no server tick needed.
    this.state.phaseEndTime = Date.now() + (dur * 1000);

    // Single timeout — drives _endGame when the global clock expires.
    // _clearAllTimers() (called inside _transitionTo) will cancel this if
    // the host ends the game early or a phase transition fires first.
    this._tickInterval = setTimeout(() => {
      this._tickInterval = null;
      this._endGame();
    }, dur * 1000);
  }

  // ════════════════════════════════════════
  // BLITZ REVEAL
  // All vote aggregation is server-side.
  // Result is broadcast once per question.
  // ════════════════════════════════════════

  _scheduleBlitzRevealTimeout(questionIndex) {
    if (this._blitzRevealTimer) clearTimeout(this._blitzRevealTimer);
    const dur = (this.state.settings.blitzTimerDuration || 12) * 1000 + 1000; // +1s grace
    this._blitzRevealTimer = setTimeout(() => {
      if (this.blitzRound && !this.blitzRound.revealSent) {
        this._sendBlitzReveal(questionIndex);
      }
    }, dur);
  }

  _sendBlitzReveal(questionIndex) {
    if (!this.blitzRound || this.blitzRound.revealSent) return;
    this.blitzRound.revealSent = true;

    if (this._blitzRevealTimer) {
      clearTimeout(this._blitzRevealTimer);
      this._blitzRevealTimer = null;
    }

    const q = this.activeQuestions[questionIndex];
    if (!q) return;

    const answers  = Object.values(this.blitzRound.answers);
    const aAnswers = answers.filter(a => a.team === 'A');
    const bAnswers = answers.filter(a => a.team === 'B');

    const majority = (teamAnswers) => {
      if (!teamAnswers.length) return { vote: -1, perfect: false, deadlock: false, votes: {} };
      const tally = {};
      teamAnswers.forEach(a => { tally[a.answer] = (tally[a.answer] || 0) + 1; });
      const maxCount = Math.max(...Object.values(tally));
      const top = Object.keys(tally).filter(k => tally[k] === maxCount).map(Number);
      if (top.length > 1) return { vote: -1, perfect: false, deadlock: true, votes: tally };
      const vote    = top[0];
      const perfect = teamAnswers.every(a => a.answer === q.answer);
      return { vote, perfect, deadlock: false, votes: tally };
    };

    const aRes    = majority(aAnswers);
    const bRes    = majority(bAnswers);
    const correct = q.answer;

    const aWin    = !aRes.deadlock && aRes.vote === correct;
    const bWin    = !bRes.deadlock && bRes.vote === correct;
    const aPoints = aRes.deadlock ? 0 : aRes.perfect ? 25 : aWin ? 10 : 0;
    const bPoints = bRes.deadlock ? 0 : bRes.perfect ? 25 : bWin ? 10 : 0;

    // ── Server-authoritative team score accumulation ──
    this.state.teamScoreA += aPoints;
    this.state.teamScoreB += bPoints;

    const isLastQuestion = questionIndex >= this.activeQuestions.length - 1;
    const isTie = isLastQuestion &&
                  this.state.teamScoreA === this.state.teamScoreB &&
                  !this.state.inSuddenDeath;

    this.broadcast('blitzReveal', {
      q:             questionIndex,
      questionText:  q.q,
      correctAnswer: correct,
      aVote:    aRes.vote,  aVotes:   aRes.votes,
      aDeadlock: aRes.deadlock, aPerfect: aRes.perfect, aPoints,
      bVote:    bRes.vote,  bVotes:   bRes.votes,
      bDeadlock: bRes.deadlock, bPerfect: bRes.perfect, bPoints,
      // Running totals — clients never accumulate, always trust these
      teamScoreA: this.state.teamScoreA,
      teamScoreB: this.state.teamScoreB,
    });

    // ── Sudden death (server-driven) ──
    // Cap at MAX_SUDDEN_DEATH rounds to prevent infinite tie loops.
    // After the cap, the game ends as a draw (clients display tied scores).
    const MAX_SUDDEN_DEATH = 3;
    if (isTie) {
      this.state.inSuddenDeath = true;
      this._suddenDeathRound = (this._suddenDeathRound || 0) + 1;

      // FIX 2: _transitionTo clears all timers before scheduling the next step.
      const revealDelayMs = (REVEAL_DURATION + 0.5) * 1000;
      if (this._suddenDeathRound > MAX_SUDDEN_DEATH) {
        // Too many ties — end as a draw after the reveal delay.
        this._transitionTo('answer_reveal', revealDelayMs, () => this._endGame());
      } else {
        this._transitionTo('answer_reveal', revealDelayMs, () => {
          const sdQ       = this.activeQuestions[0];
          const sdWrapped = { ...sdQ, q: '⚡ SUDDEN DEATH: ' + sdQ.q };
          this.activeQuestions.push(sdWrapped);

          this.blitzRound = {
            questionIndex: this.activeQuestions.length - 1,
            answers:       {},
            revealSent:    false,
          };
          this._scheduleBlitzRevealTimeout(this.blitzRound.questionIndex);

          // Phase machine: advance to new blitz question.
          this.state.questionIndex = this.blitzRound.questionIndex;
          // _transitionTo will be called inside _startQuestion, but we call it
          // directly here to also send the blitzSuddenDeath broadcast atomically.
          this._transitionTo('question', (this.state.settings.blitzTimerDuration || 12) * 1000,
            () => this._onQuestionTimeout(this.blitzRound.questionIndex));
          this._tickInterval = this._phaseTimer; // mirror for _clearTickInterval callers

          this.broadcast('blitzSuddenDeath', {
            question:      sdWrapped,
            questionIndex: this.blitzRound.questionIndex,
          });
        });
      }

    } else if (isLastQuestion) {
      // Last question revealed, no tie — end the game after the reveal delay.
      // FIX 2: _transitionTo is the single scheduler — no manual _clearPhaseTimer needed.
      this._transitionTo('answer_reveal', (REVEAL_DURATION + 0.5) * 1000, () => this._endGame());

    } else {
      // ── BUG 3 FIX: Mid-game blitz question — server drives next question ──
      // Fix 4c removed the client's countdown-driven question advancement.
      // The server must now schedule the transition to the next blitz question.
      // We go: answer_reveal (4s) → question (blitzTimer) → _sendBlitzReveal again.
      const nextIndex = questionIndex + 1;
      const blitzDur  = (this.state.settings.blitzTimerDuration || 12) * 1000;
      const revealMs  = (REVEAL_DURATION + 0.5) * 1000;

      this._transitionTo('answer_reveal', revealMs, () => {
        // Set up the blitzRound tracker for the next question BEFORE transitioning,
        // so blitzAnswer submissions for the new question are accepted immediately.
        this.blitzRound = {
          questionIndex: nextIndex,
          answers:       {},
          revealSent:    false,
        };
        this.state.questionIndex = nextIndex;

        // Transition to the next question phase.
        // _transitionTo's callback fires _sendBlitzReveal when the timer expires
        // (all players didn't answer in time). If all players answer before the
        // timer, blitzAnswer handler calls _sendBlitzReveal early — the revealSent
        // guard makes the _transitionTo callback a safe no-op in that case.
        this._transitionTo('question', blitzDur, () => {
          if (this.blitzRound && !this.blitzRound.revealSent) {
            this._sendBlitzReveal(nextIndex);
          }
        });
        this._tickInterval = this._phaseTimer; // mirror for _clearAllTimers
      });
    }
  }

  // ════════════════════════════════════════
  // HELPERS
  // ════════════════════════════════════════

  _isHost(client) {
    // hostSessionId is the single source of truth for host identity.
    // The PlayerState.isHost flag is a display hint only — never use it for auth.
    return client.sessionId === this.hostSessionId;
  }

  // Cryptographically secure 32-char hex token (128 bits of entropy).
  // Uses Node's built-in crypto module — Math.random() is NOT used here
  // because it is predictable and would allow token-prediction attacks.
  _generateToken() {
    return randomBytes(16).toString('hex');
  }

  // Recalculate blitz team counts from actual player state.
  // Called at game start and round reset to prevent count drift from
  // disconnects, reconnects, or team switches that weren't perfectly tracked.
  _recalcBlitzTeamCounts() {
    let a = 0, b = 0;
    this.state.players.forEach((p) => {
      if (p.isHost || p.exited) return;
      if (p.team === 'A') a++;
      else if (p.team === 'B') b++;
    });
    this.state.blitzTeamCountA = a;
    this.state.blitzTeamCountB = b;
  }

  // Recalculate _activePlayerCount from ground truth.
  // Called at game start so any lobby-phase drift (exits, late joins) is corrected
  // before the counter is used for _checkAllFinished comparisons.
  _recalcActiveCount() {
    let count = 0;
    this.state.players.forEach((p) => {
      if (!p.isHost && !p.exited) count++;
    });
    this._activePlayerCount = count;
  }

  // Called after every elimination or finish event.
  // Uses _activePlayerCount (maintained incrementally) and a simple finished/eliminated
  // counter so we never spread the entire players map on every answer submission.
  _checkAllFinished() {
    if (this.state.phase === 'results' || this.state.phase === 'waiting_next_round') return;
    if (this._activePlayerCount <= 0) return;

    const mode = this.state.settings.gameMode;

    let doneCount  = 0;
    let aliveCount = 0;
    let lastAlive  = null;
    this.state.players.forEach((p) => {
      if (p.isHost || p.exited) return;
      if (p.finished || p.eliminated) {
        doneCount++;
      } else {
        aliveCount++;
        lastAlive = p;
      }
    });

    // ── Survival: last-man-standing rule ──
    // When exactly one player remains alive, they win the moment they answer
    // their next question — regardless of correct/wrong — even if more
    // questions remain. We detect this here: if aliveCount === 1 and that
    // player has answered at least one question past the eliminated group,
    // end the game immediately and crown them winner.
    if (mode === 'survival' && aliveCount === 1 && lastAlive) {
      // Find the highest answeredIndex among all eliminated players to know
      // when the last man has "answered one more than everyone else".
      let maxElimAnswered = -1;
      this.state.players.forEach((p) => {
        if (p.isHost || p.exited) return;
        if (p.eliminated) maxElimAnswered = Math.max(maxElimAnswered, p.answeredIndex);
      });
      // The moment the last alive player's answeredIndex exceeds the highest
      // eliminated player's answeredIndex, they have answered "one more" — game over.
      if (lastAlive.answeredIndex > maxElimAnswered) {
        lastAlive.finished  = true;
        lastAlive.finishedAt = Date.now();
        this.broadcast('allFinished', {});
        this._endGame();
        return;
      }
      // Last man hasn't answered their "winning" question yet — wait.
      return;
    }

    if (doneCount >= this._activePlayerCount) {
      this.broadcast('allFinished', {});
      this._endGame();
    }
  }

  _applySettings(s) {
    if (!s) return;
    const st = this.state.settings;
    if (s.gameMode             !== undefined) st.gameMode             = s.gameMode;
    if (s.scoringMode          !== undefined) st.scoringMode          = s.scoringMode;
    if (s.questionCount        !== undefined) st.questionCount        = s.questionCount;
    if (s.timerDuration        !== undefined) st.timerDuration        = s.timerDuration;
    if (s.blitzTimerDuration   !== undefined) st.blitzTimerDuration   = s.blitzTimerDuration;
    if (s.lightningQDuration   !== undefined) st.lightningQDuration   = s.lightningQDuration;
    if (s.survivalTimerDuration!== undefined) st.survivalTimerDuration= s.survivalTimerDuration;
    if (s.teamAName            !== undefined) st.teamAName            = s.teamAName;
    if (s.teamBName            !== undefined) st.teamBName            = s.teamBName;
  }

  _getSettingsPlain() {
    const s = this.state.settings;
    return {
      gameMode:              s.gameMode,
      scoringMode:           s.scoringMode,
      questionCount:         s.questionCount,
      timerDuration:         s.timerDuration,
      blitzTimerDuration:    s.blitzTimerDuration,
      lightningQDuration:    s.lightningQDuration,
      survivalTimerDuration: s.survivalTimerDuration,
      teamAName:             s.teamAName,
      teamBName:             s.teamBName,
    };
  }

  _getPlayersPlain() {
    const out = {};
    this.state.players.forEach((p, id) => {
      if (!p.isHost) out[id] = {
        id, nickname: p.nickname, score: p.score,
        correctCount: p.correctCount, finished: p.finished,
        eliminated: p.eliminated, team: p.team,
        blitzCorrectCount: p.blitzCorrectCount,
        finishedAt: p.finishedAt,
      };
    });
    return out;
  }

  _clearPhaseTimer() {
    if (this._phaseTimer) { clearTimeout(this._phaseTimer); this._phaseTimer = null; }
  }

  _clearTickInterval() {
    if (this._tickInterval) {
      clearTimeout(this._tickInterval);
      clearInterval(this._tickInterval); // belt-and-suspenders for any legacy call sites
      this._tickInterval = null;
    }
  }

  _clearAllTimers() {
    this._clearPhaseTimer();
    this._clearTickInterval();
    if (this._blitzRevealTimer) { clearTimeout(this._blitzRevealTimer); this._blitzRevealTimer = null; }
  }
}

module.exports = { QuizRoom };
